reporter: "xcode"
line_length:
  - 200
  - 300
file_length:
  - 1000
  - 2000
cyclomatic_complexity:
  - 20
type_body_length:
  - 600
  - 2000
disabled_rules:
  - trailing_newline
  - nesting
  - identifier_name
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count # pode ser que tenha que desativar essa regra em alguns casos
  - colon
  - comma
  - control_statement
  - empty_parameters
  - void_return
  - closing_brace
included:
  - productList
excluded:
  - Pods
