source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!

target 'productList' do
  use_frameworks!

  target 'productListTests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'
  end

  target 'productListUITests' do
    # Pods for testing
  end

end
